version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=chatserver
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"
    depends_on:
      - mongo
  app:
    build: .
    #   volume specification is needed for hot reload support other wise hot reload
    #   wont trigger
    volumes:
      - ./:/usr/src/app/

    ports:
      - "8080:8080"
    depends_on:
      - mongo
